spring.profiles.active=dev

# Spring Batch cria as tabelas de metadados automaticamente
spring.batch.jdbc.initialize-schema=always

# evita rodar o job automaticamente ao subir
spring.batch.job.enabled=false

spring.application.name=lancamentos
spring.datasource.url=jdbc:postgresql://localhost:5432/lancamentos
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.max.block.ms=60000

spring.kafka.producer.retries=3
spring.kafka.producer.acks=all

ingestao.arquivo.caminho=/app/arquivos/lancamentos.csv